#!/usr/bin/env pwsh
# ================================================================
# نشر النظام المحاسبي - دليل خطوة بخطوة
# ================================================================
# الاستخدام: .\setup-online.ps1
# ================================================================

$ErrorActionPreference = "Stop"

function Write-Step($num, $title) {
  Write-Host "`n[$num] $title" -ForegroundColor Cyan
  Write-Host ("=" * 60) -ForegroundColor DarkGray
}

function Write-Success($msg) { Write-Host "✓ $msg" -ForegroundColor Green }
function Write-Info($msg)    { Write-Host "  $msg" -ForegroundColor Yellow }
function Write-Cmd($msg)     { Write-Host "  > $msg" -ForegroundColor White }

Write-Host @"

 ╔═══════════════════════════════════════════════════════════╗
 ║      النظام المحاسبي المتكامل - دليل النشر الآلي          ║
 ║      Integrated Accounting System - Deployment Guide       ║
 ╚═══════════════════════════════════════════════════════════╝

"@ -ForegroundColor Cyan

# ================================================================
Write-Step "1" "التحقق من الأدوات المطلوبة"
# ================================================================

$tools = @{ "node" = "Node.js"; "git" = "Git"; "npm" = "NPM" }
foreach ($tool in $tools.Keys) {
  try {
    $ver = & $tool --version 2>&1
    Write-Success "$($tools[$tool]): $ver"
  } catch {
    Write-Host "✗ $($tools[$tool]) غير مثبت" -ForegroundColor Red
    Write-Info "قم بتثبيته من: https://nodejs.org"
    exit 1
  }
}

# ================================================================
Write-Step "2" "بناء المشروع محلياً"
# ================================================================

$projectRoot = Split-Path $MyInvocation.MyCommand.Path

Write-Info "بناء Backend..."
Push-Location (Join-Path $projectRoot "backend")
npm install --ignore-scripts --silent 2>&1 | Out-Null
npx tsc 2>&1 | Out-Null
Write-Success "Backend built successfully"
Pop-Location

Write-Info "بناء Frontend..."
Push-Location (Join-Path $projectRoot "frontend")
npm install --silent 2>&1 | Out-Null
npm run build 2>&1 | Out-Null
Write-Success "Frontend built successfully"
Pop-Location

# ================================================================
Write-Step "3" "إعداد قاعدة البيانات على Supabase"
# ================================================================

Write-Info @"
ستحتاج إلى:
  1. حساب مجاني على https://supabase.com
  2. إنشاء مشروع جديد
  3. نسخ رابط قاعدة البيانات (DATABASE_URL)
"@

Write-Host ""
$openBrowser = Read-Host "هل تريد فتح Supabase الآن؟ [Y/N]"
if ($openBrowser -eq 'Y' -or $openBrowser -eq 'y') {
  Start-Process "https://supabase.com/dashboard/new/project"
  Write-Info "تم فتح Supabase في المتصفح"
  Write-Info "أنشئ مشروعاً جديداً باسم: accounting-bg"
}

Write-Host ""
Write-Info "بعد إنشاء المشروع على Supabase:"
Write-Info "1. اذهب إلى: Settings → Database → Connection string → URI"
Write-Info "2. انسخ الرابط (يبدأ بـ postgresql://)"
Write-Host ""

$dbUrl = Read-Host "الصق DATABASE_URL هنا (أو اضغط Enter للتخطي)"

if ($dbUrl) {
  # Run schema on Supabase
  Write-Info "تشغيل schema على قاعدة البيانات..."
  
  $schemaPath = Join-Path $projectRoot "database\schema.postgresql.sql"
  $schema = Get-Content $schemaPath -Raw -Encoding UTF8
  
  # Use psql if available
  $psql = Get-Command psql -ErrorAction SilentlyContinue
  if ($psql) {
    $env:PGPASSWORD = ($dbUrl -replace '.*:([^@]+)@.*', '$1')
    Write-Cmd "psql `"$dbUrl`" -f database/schema.postgresql.sql"
    & psql $dbUrl -f $schemaPath 2>&1 | Select-Object -Last 5
    Write-Success "Schema applied successfully!"
  } else {
    Write-Info "psql غير متوفر. يرجى تشغيل الـ SQL يدوياً:"
    Write-Info "1. افتح Supabase → SQL Editor"
    Write-Info "2. انسخ محتوى ملف: database/schema.postgresql.sql"
    Write-Info "3. شغّل الاستعلام"
    Start-Process "https://supabase.com/dashboard"
  }
  
  # Save to .env file
  $envContent = @"
# Generated by setup-online.ps1 on $(Get-Date -Format 'yyyy-MM-dd')
DATABASE_URL=$dbUrl
NODE_ENV=production
PORT=3000
JWT_SECRET=$(New-Guid)-$(New-Guid)
REFRESH_SECRET=$(New-Guid)-$(New-Guid)
JWT_EXPIRES_IN=24h
REFRESH_EXPIRES_IN=7d
CLOUD_PROVIDER=none
"@
  $envContent | Set-Content (Join-Path $projectRoot "backend\.env.generated") -Encoding UTF8
  Write-Success "تم حفظ الإعدادات في backend/.env.generated"
}

# ================================================================
Write-Step "4" "نشر Backend على Render"
# ================================================================

Write-Info @"
Render.com - منصة مجانية للـ Backend
  - خطة مجانية: 750 ساعة/شهر
  - PostgreSQL مجاني لمدة 90 يوم
"@

Write-Host ""
$openRender = Read-Host "هل تريد فتح Render الآن؟ [Y/N]"
if ($openRender -eq 'Y' -or $openRender -eq 'y') {
  Start-Process "https://render.com/deploy?repo=https://github.com/BGHUSSEINSASH/accounting-bg"
  Write-Info "تم فتح Render في المتصفح"
}

Write-Host ""
Write-Info "إعدادات Render:"
Write-Cmd "Name:          accounting-bg-backend"
Write-Cmd "Root Directory: backend"
Write-Cmd "Build Command:  npm install --ignore-scripts && npm run build"
Write-Cmd "Start Command:  node dist/app.js"
Write-Host ""
Write-Info "Environment Variables المطلوبة:"
if ($dbUrl) {
  Write-Cmd "DATABASE_URL = $dbUrl"
} else {
  Write-Cmd "DATABASE_URL = (من Supabase)"
}
Write-Cmd "NODE_ENV = production"
Write-Cmd "JWT_SECRET = (أي نص عشوائي طويل)"
Write-Cmd "REFRESH_SECRET = (أي نص عشوائي طويل آخر)"

$backendUrl = Read-Host "`nبعد النشر، أدخل URL الـ Backend (مثال: https://accounting-bg-backend.onrender.com)"

# ================================================================
Write-Step "5" "نشر Frontend على Vercel"
# ================================================================

Write-Info @"
Vercel.com - منصة مجانية للـ Frontend
  - نشر تلقائي عند كل push لـ GitHub
  - CDN عالمي سريع
"@

Write-Host ""
$openVercel = Read-Host "هل تريد فتح Vercel الآن؟ [Y/N]"
if ($openVercel -eq 'Y' -or $openVercel -eq 'y') {
  Start-Process "https://vercel.com/new"
  Write-Info "تم فتح Vercel في المتصفح"
}

Write-Host ""
Write-Info "إعدادات Vercel:"
Write-Cmd "Repository:    BGHUSSEINSASH/accounting-bg"
Write-Cmd "Root:          frontend"
Write-Cmd "Build Command: npm run build"
Write-Cmd "Output Dir:    dist"
Write-Host ""
Write-Info "Environment Variables:"
if ($backendUrl) {
  Write-Cmd "VITE_API_BASE_URL = $backendUrl/api"
} else {
  Write-Cmd "VITE_API_BASE_URL = https://accounting-bg-backend.onrender.com/api"
}

$frontendUrl = Read-Host "`nبعد النشر، أدخل URL الـ Frontend (مثال: https://accounting-bg.vercel.app)"

# ================================================================
Write-Step "6" "تحديث CORS في Render"
# ================================================================

if ($frontendUrl -and $backendUrl) {
  Write-Info "يجب إضافة هذا المتغير في Render:"
  Write-Cmd "CORS_ORIGIN = $frontendUrl"
  Write-Cmd "FRONTEND_ORIGIN = $frontendUrl"
  Write-Info "اذهب إلى Render → Service → Environment → Add variables above"
}

# ================================================================
Write-Step "7" "تحديث GitHub Actions Secrets"
# ================================================================

Write-Info "لتفعيل النشر التلقائي، أضف هذه Secrets في GitHub:"
Start-Process "https://github.com/BGHUSSEINSASH/accounting-bg/settings/secrets/actions"

Write-Host ""
if ($backendUrl) {
  $hook = "$backendUrl/deploys"
  Write-Cmd "RENDER_DEPLOY_HOOK = (من Render → Settings → Deploy Hook)"
}
if ($frontendUrl) {
  Write-Cmd "VERCEL_TOKEN = (من vercel.com/account/tokens)"
  Write-Cmd "VITE_API_BASE_URL = $($backendUrl)/api"
}

# ================================================================
Write-Step "8" "ملخص النشر"
# ================================================================

Write-Host @"

 ════════════════════════════════════════════════════════════
"@ -ForegroundColor Green

if ($frontendUrl) { Write-Success "Frontend:  $frontendUrl" }
if ($backendUrl)  { Write-Success "Backend:   $backendUrl" }
Write-Success "GitHub:    https://github.com/BGHUSSEINSASH/accounting-bg"
Write-Success "CI/CD:     GitHub Actions (تلقائي عند كل push)"

Write-Host @"

 بيانات الدخول الافتراضية:
   المستخدم: admin
   كلمة المرور: 123456

 للمساعدة، راجع: DEPLOYMENT.md

 ════════════════════════════════════════════════════════════
"@ -ForegroundColor Cyan
